### ISSUE TITLE
Excel files are not rendering correctly.

### ISSUE THREAD

**Issue by mtoor123** [GleamTech/DocumentUltimate#1]
Data in excel files is not shown in correct order and if the data in a cell exceeds the visible boundaries of that particular cell then only that part of data is shown that is visible. Also empty pages are shown too. As it should only show pages with data.

**Comment by GleamTech** [comment]
FYI, spreadsheet handling was improved after Version 2.5.0 - March 14, 2017:

- **Added:** SpreadsheetInputOptions class for prodiving spreadsheet format specific options. For example setting
  property RenderColumnsFitToPages = 1, will make all columns of a spreadsheet fit to the same page. SheetRange property
  allows you to choose specific sheet numbers or predefined keywords like (works similar to PageRange class):
  
  - "all" -> keyword representing all sheet numbers.
  
  - "active" -> keyword representing the active sheet number.
  
  -  "visible" -> keyword representing visible sheet numbers.

  SpreadsheetInputOptions class has many other options related to rendering of spreadsheets.

- **Added:** DocumentViewer.InputOptions property which is a collection. For example an instance of the new 
  SpreadsheetInputOptions class can be added to this property. By default the viewer will use the below instance
  for best results when displaying a spreadsheet document:

  new SpreadsheetInputOptions
  {
	  OutputSheetRange = new SheetRange("visible"),
	  RenderColumnsFitToPages = 1
  };

  DocumentViewer.InputOptions property is implemented as a collection because in future we may provide more format 
  specific options and the viewer will get the matching options automatically from this collection.
