### ISSUE TITLE
Wrong document being served from Cache

### ISSUE THREAD

**Issue by BenEdgeContra** [GleamTech/DocumentUltimate#11]
Using: `<package id="GleamTech.DocumentUltimate" version="6.6.1" targetFramework="net48" />`

We have noticed that sometimes the wrong document is displayed in the document viewer.  After renaming the folder where the document cache is stored (hence clearing the cache) the correct document is displayed.

Our implementation is pretty basic:
```
var documentViewer = new DocumentViewer
{
    Width = 1000,
    Height = 800,
    SidePaneVisible = false,
    PageFitMode = DocumentViewerPageFitMode.Zoom
};
// Get file from blob
var blobStream = BlobUtility.DownloadBlob(downloadFilePath);
var byteArray = DocumentController.ReadFully(blobStream);
var fileProvider = new MemoryFileProvider(file: doc.Ext.ToLower(), bytes: byteArray, dateModified: null);
documentViewer.Document = fileProvider;
```

**Comment by GleamTech** [comment]
Since v6.4 we are using FileProvider API. There are many built-in file providers e.g. FileSystemFileProvider, UrlFileProvider, DataUrlFileProvider, StreamFileProvider, MemoryFileProvider, DatabaseFileProvider, AssemblyResourceFileProvider, TemporaryFileProvider.

For generating the cache key, to uniquely identify a document file, we use a string combination of file extension, file size and file date, this way cache collisions do not occur and we can resuse the cached file even if the file name before extension is changed (file1.docx and file2.docx have same cache key because it's still the same document according to file extension, file size and file date).

File providers like FileSystemFileProvider (a file on disk, on Amazon S3, on Azure) can provide file size and file date automatically however some file providers will not have this knowledge, e.g. StreamFileProvider, MemoryFileProvider (how could they know date modified of your data in a byte array or a stream?).

So for this purpose, these kind of providers have an additional property or constructor argument named DateModified and/or Size. You need to specify these to ensure you uniquely identify a document:

```c#
//Optional parameters (used for detailed file info, e.g. for generating better cache keys)
documentViewer.Document = new StreamFileProvider(
    "SomeFolder/SomeFile.ext", 
    yourStream,
    yourFileDateModified,
    yourFileSize //Provide size only if your stream is not seekable
);
```

```c#
//Optional parameters (used for detailed file info, e.g. for generating better cache keys)
documentViewer.Document = new MemoryFileProvider(
    "SomeFolder/SomeFile.ext", 
    yourMemoryStream,
    yourFileDateModified
);
```

```c#
//Optional parameters (used for detailed file info, e.g. for generating better cache keys)
documentViewer.Document = new MemoryFileProvider(
    "SomeFolder/SomeFile.ext", 
    yourByteArray,
    yourFileDateModified
);
```
