### ISSUE TITLE
.NET Core assembly error

### ISSUE THREAD

**Issue by mtinnes** [GleamTech/DocumentUltimate#5]
I'm trying to use DocumentUltimate 4.0.8 for converting a PPT to JPG in an ASP.NET Core project. I get the following error when trying to execute any GleamTech code. It appears there is some static initialization being done which references an assembly not available in .NET Core. I also have the GleamTech.Core assembly references in our project.

```
System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for 'GleamTech.AssemblyResolver.AssemblyResolver' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at GleamTech.AssemblyResolver.AssemblyResolver..cctor()
   --- End of inner exception stack trace ---
   at GleamTech.AssemblyResolver.AssemblyResolver.Register(Assembly primaryAssembly, String configurationResourceName, String configurationVersion)
   at AssemblyBootstrap.Register()
   at AssemblyBootstrap.Initialize()
```

**Comment by GleamTech** [comment]
Note that as of current version DocumentUltimate only works with a "ASP.NET on .NET Framework" project.

"ASP.NET Core on .NET Core" is a different platform and it's not supported yet because it requires porting all the code from .NET Framework runtime to .NET Core runtime so it requires a new DLL and .NET Core runtime does not provide all of the APIs yet. Minimum supported version is ASP.NET Core MVC 2.0.3 on .NET Framework 4.6.1 (this is because 2.0.3 fixes a bug related to referencing external DLLs in a razor page).
