### ISSUE TITLE
DocumentUltimate not working with asp.net core 3

### ISSUE THREAD

**Issue by AmrAlsawy** [GleamTech/DocumentUltimate#6]
![image](https://user-images.githubusercontent.com/57393758/68692848-dec9b280-057e-11ea-8da2-ecb77999ec63.png)

**Comment by GleamTech** [comment]
We have a new release which works good with ASP.NET Core 2.0, 2.1 and 2.2.
But yes, currently there seems to be a problem with ASP.NET Core 3.0 compatibility (even with this new release). This will be fixed in next release.

## Version 5.1.0 - November 13, 2019

  - **Fixed:** "Object reference not set to an instance of an object" error at app.UseGleamTech() line with ASP.NET Core 2.1 and 2.2 projects.
    Now ASP.NET Core 2.1 and 2.2 compatiblity is ensured.

**Comment by GleamTech** [comment]
FYI,
This is now fixed.

## Version 5.1.1 - November 14, 2019

  - **Fixed:** ASP.NET Core 3.0 compatibility.

**Comment by AmrAlsawy** [comment]
Wonderful, thanks
